#!/bin/bash

## FUNCTIONS ##
#Upgrade using pacman
pacman_f() { 
    sudo pacman -Syu
    exit
} 

#Upgrade using yay
yay_f() { 
    yay -Syu
    exit
} 

##END OF FUNCTIONS##

#Check for news if informant is installed
if which informant > /dev/null; then
echo "Checking for news from Arch linux using informant..."
sudo informant read
echo "Done checking for news..."
fi

#Continue?
while true; do
    read -p "Do you wish to make a snapshot & continue with the upgrade?" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

#Stamp it!
TIMESTAMP=`date +"%Y-%m-%d-%H%M%S"`

#Create snapshot
echo "Creating snapshot..."
sudo btrfs subvolume snapshot -r / /.snapshots/$TIMESTAMP

#Update GRUB
echo "Updating GRUB..."
sudo grub-mkconfig -o /boot/grub/grub.cfg

#Upgrade with...?
PS3="Select option: "

select opt in pacman yay quit; do

  case $opt in
    pacman)
	pacman_f
      ;;
    yay)
	yay_f
      ;;
    quit)
      	break
      ;;
    *) 
      echo "Invalid option $REPLY"
      ;;
  esac
done
